<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
    <meta name="robots" content="noindex,nofollow">
    <meta name="theme-color" content="#123f34">
    <title>Admin · VerseHub</title>
    <style>
        :root{--bg:#f3efe6;--card:#fffaf1;--ink:#25231e;--muted:#6d685f;--forest:#155a48;--deep:#0e3f34;--mint:#dce9df;--line:#d8cfbe;--gold:#c69231;--danger:#a83f45;--shadow:0 18px 55px rgba(45,38,28,.10)}
        *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.5 Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}button,input,select,textarea{font:inherit}button{cursor:pointer}.hidden{display:none!important}
        .login{min-height:100dvh;display:grid;place-items:center;padding:28px}.login-card{width:min(440px,100%);padding:36px;border:1px solid var(--line);border-radius:30px;background:var(--card);box-shadow:var(--shadow);text-align:center}.logo{width:64px;height:64px;border-radius:18px;margin:0 auto 20px}.login h1{font:700 38px/1 Georgia,serif;margin:0 0 12px}.login p{color:var(--muted)}
        .button{min-height:46px;display:inline-flex;align-items:center;justify-content:center;gap:8px;padding:0 18px;border:0;border-radius:999px;background:var(--forest);color:#fff;font-weight:800;text-decoration:none}.button.secondary{background:transparent;color:var(--forest);border:1px solid var(--line)}.button.danger{background:var(--danger)}.button.small{min-height:36px;padding:0 13px;font-size:12px}.button:disabled{opacity:.5}
        .app{min-height:100dvh}.sidebar{position:fixed;inset:0 auto 0 0;width:248px;padding:calc(24px + env(safe-area-inset-top)) 18px 24px;background:var(--deep);color:#fff;z-index:20}.brand{display:flex;align-items:center;gap:12px;margin:0 8px 30px;font-weight:900}.brand img{width:42px;height:42px;border-radius:12px}.nav{display:grid;gap:7px}.nav button{display:flex;align-items:center;gap:11px;width:100%;min-height:44px;padding:0 13px;border:0;border-radius:13px;background:transparent;color:#cde0d8;text-align:left;font-weight:750}.nav button.active,.nav button:hover{background:rgba(255,255,255,.12);color:#fff}.sidebar-foot{position:absolute;left:18px;right:18px;bottom:20px;color:#b8cdc5;font-size:12px}.sidebar-foot button{margin-top:10px;color:#fff;background:none;border:0;padding:0;text-decoration:underline}
        main{margin-left:248px;padding:36px max(30px,4vw) 70px}.top{display:flex;align-items:flex-start;justify-content:space-between;gap:20px;margin-bottom:28px}.eyebrow{color:var(--forest);font-size:11px;font-weight:900;letter-spacing:.12em;text-transform:uppercase}h1{font:700 clamp(34px,5vw,56px)/1 Georgia,serif;margin:8px 0 0}.top small{color:var(--muted)}
        .view{display:none}.view.active{display:block}.metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.metric,.panel{border:1px solid var(--line);background:var(--card);border-radius:22px;box-shadow:0 8px 32px rgba(45,38,28,.04)}.metric{padding:22px}.metric strong{display:block;font:700 32px/1 Georgia,serif;color:var(--forest)}.metric span{display:block;margin-top:8px;color:var(--muted);font-size:12px;font-weight:750}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;margin-top:16px}.panel{padding:22px}.panel h2{margin:0 0 16px;font:700 24px/1.1 Georgia,serif}.panel-head,.toolbar{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}.toolbar{margin-bottom:16px}.field{width:100%;min-height:46px;padding:10px 13px;border:1px solid var(--line);border-radius:13px;background:#fffdf8;color:var(--ink)}textarea.field{min-height:92px;resize:vertical}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.span-2{grid-column:span 2}.list{display:grid;gap:10px}.item{padding:15px;border:1px solid var(--line);border-radius:16px;background:#fffdf8}.item-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.item strong{display:block}.meta{color:var(--muted);font-size:12px}.actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}.pill{display:inline-flex;padding:4px 9px;border-radius:999px;background:var(--mint);color:var(--deep);font-size:11px;font-weight:850}.pill.danger{background:#f5dfe0;color:var(--danger)}.empty{padding:28px;color:var(--muted);text-align:center}.notice{padding:13px 15px;border-radius:13px;background:var(--mint);color:var(--deep);margin-bottom:14px}.error{background:#f5dfe0;color:var(--danger)}
        .bottom-nav{display:none}.toast{position:fixed;right:22px;bottom:22px;z-index:50;max-width:360px;padding:14px 17px;border-radius:14px;background:var(--deep);color:#fff;box-shadow:var(--shadow)}
        @media(max-width:980px){.metrics{grid-template-columns:repeat(2,1fr)}.grid{grid-template-columns:1fr}}
        @media(max-width:720px){.sidebar{display:none}main{margin:0;padding:calc(24px + env(safe-area-inset-top)) 14px calc(94px + env(safe-area-inset-bottom))}.top{align-items:center}.top small{display:none}.metrics{gap:9px}.metric{padding:16px;border-radius:17px}.metric strong{font-size:26px}.panel{padding:16px;border-radius:18px}.form-grid{grid-template-columns:1fr}.span-2{grid-column:auto}.bottom-nav{position:fixed;display:flex;left:8px;right:8px;bottom:max(8px,env(safe-area-inset-bottom));z-index:30;overflow-x:auto;padding:7px;border-radius:20px;background:var(--deep);box-shadow:var(--shadow)}.bottom-nav button{flex:1 0 70px;min-height:50px;border:0;border-radius:14px;background:transparent;color:#bfd4cc;font-size:10px;font-weight:800}.bottom-nav button.active{background:rgba(255,255,255,.14);color:#fff}.bottom-nav b{display:block;font-size:18px}.toast{left:14px;right:14px;bottom:86px}.item-head{display:block}.item-head>.pill{margin-top:8px}}
    </style>
</head>
<body>
<section id="login" class="login">
    <div class="login-card"><img class="logo" src="/assets/versehub-icon.png" alt=""><span class="eyebrow">Área protegida</span><h1>VerseHub Admin</h1><p>Entre com a conta Google que possui permissão de administrador.</p><a id="loginButton" class="button" href="#">Entrar com Google</a><p id="loginError" class="notice error hidden"></p></div>
</section>

<div id="app" class="app hidden">
    <aside class="sidebar"><div class="brand"><img src="/assets/versehub-icon.png" alt=""><span>VerseHub Admin</span></div><nav class="nav" id="desktopNav"></nav><div class="sidebar-foot"><span id="adminIdentity"></span><button id="logout">Sair com segurança</button></div></aside>
    <main>
        <header class="top"><div><span class="eyebrow">Painel administrativo</span><h1 id="viewTitle">Visão geral</h1></div><small id="clock"></small></header>
        <section id="view-dashboard" class="view active"><div id="metrics" class="metrics"></div><div class="grid"><article class="panel"><h2>Ações prioritárias</h2><div id="priorities" class="list"></div></article><article class="panel"><h2>Operação</h2><div id="operations" class="list"></div></article></div></section>
        <section id="view-users" class="view"><div class="panel"><div class="toolbar"><input id="userSearch" class="field" style="max-width:360px" placeholder="Buscar nome ou e-mail"><select id="userFilter" class="field" style="max-width:190px"><option value="">Todos</option><option value="admins">Admins</option><option value="banned">Banidos</option><option value="blocked">Sem criar categorias</option></select><button class="button" onclick="loadUsers()">Buscar</button></div><div id="usersList" class="list"></div></div></section>
        <section id="view-moderation" class="view"><div class="grid"><article class="panel"><div class="panel-head"><h2>Denúncias</h2><button class="button small secondary" onclick="loadReports()">Atualizar</button></div><div id="reportsList" class="list"></div></article><article class="panel"><div class="panel-head"><h2>Comentários</h2><button class="button small secondary" onclick="loadComments()">Atualizar</button></div><div id="commentsList" class="list"></div></article></div></section>
        <section id="view-daily" class="view"><div class="grid"><article class="panel"><h2>Agendar versículo</h2><form id="dailyForm" class="form-grid"><input name="publish_date" type="date" class="field" required><input name="position" type="number" min="1" max="10" value="1" class="field" required><input name="reference" class="field span-2" placeholder="Referência: João 3:16" required><input name="version" class="field" value="NVI" maxlength="10" required><input name="book_abbrev" class="field" placeholder="Sigla: jo"><textarea name="text" class="field span-2" placeholder="Texto fiel da tradução autorizada" required></textarea><input name="chapter" type="number" class="field" placeholder="Capítulo"><input name="verse_number" type="number" class="field" placeholder="Versículo"><label class="meta"><input name="is_active" type="checkbox" checked> Ativo</label><button class="button" type="submit">Agendar</button></form></article><article class="panel"><div class="panel-head"><h2>Próximos</h2><button class="button small secondary" onclick="loadDaily()">Atualizar</button></div><div id="dailyList" class="list"></div></article></div></section>
        <section id="view-push" class="view"><div class="grid"><article class="panel"><h2>Nova notificação</h2><form id="pushForm" class="form-grid"><input name="title" class="field span-2" maxlength="80" placeholder="Título" required><textarea name="body" class="field span-2" maxlength="240" placeholder="Mensagem" required></textarea><select name="audience" class="field"><option value="all">Todos os aparelhos</option><option value="public_profiles">Perfis públicos</option></select><input name="scheduled_at" type="datetime-local" class="field"><input name="reference" class="field" placeholder="Referência opcional"><input name="version" class="field" value="NVI" placeholder="Versão"><label class="meta"><input name="send_now" type="checkbox"> Enviar agora</label><button class="button" type="submit">Salvar campanha</button></form></article><article class="panel"><div class="panel-head"><h2>Campanhas</h2><span id="deviceCount" class="pill"></span></div><div id="pushList" class="list"></div></article></div></section>
        <section id="view-categories" class="view"><div class="grid"><article class="panel"><h2>Categorias pendentes</h2><div id="categoriesList" class="list"></div></article><article class="panel"><h2>Grupos pendentes</h2><div id="groupsList" class="list"></div></article></div></section>
        <section id="view-bible" class="view"><div class="panel"><div class="toolbar"><input id="bibleSearch" class="field" style="max-width:520px" placeholder="Buscar palavra ou referência"><button class="button" onclick="searchBible()">Pesquisar</button></div><p class="notice">Use somente traduções autorizadas. O painel não altera o texto bíblico; ele ajuda a localizar e programar passagens.</p><div id="bibleList" class="list"></div></div></section>
    </main>
    <nav id="mobileNav" class="bottom-nav"></nav>
</div>
<div id="toast" class="toast hidden"></div>

<script>
const API='/api'; const tabs=[['dashboard','⌂','Visão geral'],['users','♙','Pessoas'],['moderation','⚑','Moderação'],['daily','✦','Versos'],['push','◉','Push'],['categories','◈','Momentos'],['bible','⌕','Bíblia']];
let token=sessionStorage.getItem('versehub_admin_token')||''; const qs=new URLSearchParams(location.search); if(qs.get('token')){token=qs.get('token');sessionStorage.setItem('versehub_admin_token',token);history.replaceState({},'',location.pathname+location.hash)}
const $=id=>document.getElementById(id); const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(message,error=false){const el=$('toast');el.textContent=message;el.style.background=error?'#a83f45':'#0e3f34';el.classList.remove('hidden');setTimeout(()=>el.classList.add('hidden'),3500)}
async function api(path,options={}){const response=await fetch(API+path,{...options,headers:{Accept:'application/json','Content-Type':'application/json',Authorization:'Bearer '+token,...(options.headers||{})}});if(response.status===401){logout();throw new Error('Sessão expirada')}const body=response.status===204?{}:await response.json();if(!response.ok)throw new Error(body.message||Object.values(body.errors||{}).flat()[0]||'Não foi possível concluir');return body}
function logout(){sessionStorage.removeItem('versehub_admin_token');token='';$('app').classList.add('hidden');$('login').classList.remove('hidden')}
function nav(){const html=tabs.map(([id,icon,label])=>`<button data-tab="${id}" onclick="showView('${id}')"><b>${icon}</b>${label}</button>`).join('');$('desktopNav').innerHTML=html;$('mobileNav').innerHTML=html}
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+id));document.querySelectorAll('[data-tab]').forEach(v=>v.classList.toggle('active',v.dataset.tab===id));$('viewTitle').textContent=tabs.find(t=>t[0]===id)?.[2]||'Admin';location.hash=id;({dashboard:loadDashboard,users:loadUsers,moderation:()=>{loadReports();loadComments()},daily:loadDaily,push:loadPush,categories:loadCategories,bible:()=>{}}[id]||(()=>{}))()}
async function boot(){nav();$('loginButton').href=API+'/auth/google/redirect?client_redirect='+encodeURIComponent(location.origin+'/admin');if(!token)return;try{const me=await api('/auth/user');const user=me.data?.user;if(!user?.is_admin)throw new Error('Esta conta não possui permissão de administrador.');$('adminIdentity').textContent=user.name+' · '+user.email;$('login').classList.add('hidden');$('app').classList.remove('hidden');showView((location.hash||'#dashboard').slice(1))}catch(e){$('loginError').textContent=e.message;$('loginError').classList.remove('hidden');logout()}}
async function loadDashboard(){try{const {data}=await api('/admin/dashboard');const cards=[['total_users','Pessoas'],['active_users_today','Ativas hoje'],['pending_reports','Denúncias'],['banned_users','Banidas'],['classifications_today','Sentimentos hoje'],['active_push_devices','Push ativos'],['daily_verses_next_30_days','Versos agendados'],['scheduled_push_campaigns','Push agendados']];$('metrics').innerHTML=cards.map(([k,l])=>`<div class="metric"><strong>${esc(data[k]||0)}</strong><span>${l}</span></div>`).join('');$('priorities').innerHTML=`<div class="item"><strong>${data.pending_reports||0} denúncias aguardando</strong><span class="meta">Revise antes de crescer a comunidade.</span></div><div class="item"><strong>${data.pending_categories||0} categorias pendentes</strong><span class="meta">Aprovação mantém a organização.</span></div>`;$('operations').innerHTML=`<div class="item"><strong>${data.active_push_devices||0} aparelhos com push</strong></div><div class="item"><strong>${data.classifications_total||0} classificações no total</strong></div>`}catch(e){toast(e.message,true)}}
async function loadUsers(){try{const q=new URLSearchParams({search:$('userSearch').value,filter:$('userFilter').value});const {data}=await api('/admin/users?'+q);$('usersList').innerHTML=data.data.map(u=>`<div class="item"><div class="item-head"><div><strong>${esc(u.name)}</strong><span class="meta">${esc(u.email)} · nível ${u.stats?.current_level||1} · ${u.stats?.total_points||0} pontos</span></div><span class="pill ${u.is_banned?'danger':''}">${u.is_banned?'BANIDO':u.is_admin?'ADMIN':'ATIVO'}</span></div><div class="actions"><button class="button small secondary" onclick="editUser(${u.id},'${encodeURIComponent(u.name||'')}','${encodeURIComponent(u.avatar||'')}')">Nome/foto</button><button class="button small secondary" onclick="points(${u.id})">± pontos</button><button class="button small ${u.is_banned?'secondary':'danger'}" onclick="ban(${u.id},${!u.is_banned})">${u.is_banned?'Desbanir':'Banir'}</button></div></div>`).join('')||'<div class="empty">Nenhuma pessoa encontrada.</div>'}catch(e){toast(e.message,true)}}
async function editUser(id,name,avatar){name=decodeURIComponent(name);avatar=decodeURIComponent(avatar);const newName=prompt('Nome público',name);if(newName===null)return;const newAvatar=prompt('URL da foto (vazio remove)',avatar);if(newAvatar===null)return;try{await api('/admin/users/'+id+'/identity',{method:'PATCH',body:JSON.stringify({name:newName,avatar:newAvatar||null})});toast('Nome e foto atualizados');loadUsers()}catch(e){toast(e.message,true)}}
async function points(id){const value=prompt('Quantos pontos adicionar? Use número negativo para retirar.');if(value===null)return;const reason=prompt('Motivo obrigatório');if(!reason)return;try{await api('/admin/users/'+id+'/points',{method:'POST',body:JSON.stringify({points:Number(value),reason})});toast('Pontuação atualizada');loadUsers()}catch(e){toast(e.message,true)}}
async function ban(id,banned){const reason=banned?prompt('Motivo do banimento'):'';if(banned&&!reason)return;try{await api('/admin/users/'+id+'/ban',{method:'POST',body:JSON.stringify({banned,reason})});toast(banned?'Pessoa banida':'Acesso restaurado');loadUsers()}catch(e){toast(e.message,true)}}
async function loadReports(){try{const {data}=await api('/admin/moderation/reports?status=pending');$('reportsList').innerHTML=data.data.map(r=>`<div class="item"><strong>${esc(r.reason)} · ${esc(r.reportable_type)} #${r.reportable_id}</strong><span class="meta">Por ${esc(r.reporter_name)} · ${new Date(r.created_at).toLocaleString('pt-BR')}</span><p>${esc(r.details||'Sem detalhes')}</p><div class="actions"><button class="button small" onclick="resolveReport(${r.id},'actioned')">Ação tomada</button><button class="button small secondary" onclick="resolveReport(${r.id},'dismissed')">Dispensar</button></div></div>`).join('')||'<div class="empty">Nenhuma denúncia pendente.</div>'}catch(e){toast(e.message,true)}}
async function resolveReport(id,status){try{await api('/admin/moderation/reports/'+id,{method:'PATCH',body:JSON.stringify({status})});loadReports();toast('Denúncia atualizada')}catch(e){toast(e.message,true)}}
async function loadComments(){try{const {data}=await api('/admin/moderation/comments?status=published');$('commentsList').innerHTML=data.data.slice(0,30).map(c=>`<div class="item"><strong>${esc(c.reference)} · ${esc(c.user_name)}</strong><p>${esc(c.body)}</p><div class="actions"><button class="button small secondary" onclick="comment(${c.id},{is_featured:${!c.is_featured}})">${c.is_featured?'Remover destaque':'Destacar'}</button><button class="button small danger" onclick="comment(${c.id},{status:'removed'})">Remover</button></div></div>`).join('')||'<div class="empty">Nenhum comentário.</div>'}catch(e){toast(e.message,true)}}
async function comment(id,data){try{await api('/admin/moderation/comments/'+id,{method:'PATCH',body:JSON.stringify(data)});loadComments();toast('Comentário atualizado')}catch(e){toast(e.message,true)}}
async function loadDaily(){try{const {data}=await api('/admin/daily-verses');$('dailyList').innerHTML=data.map(v=>`<div class="item"><div class="item-head"><div><strong>${new Date(v.publish_date+'T12:00:00').toLocaleDateString('pt-BR')} · ${esc(v.reference)}</strong><span class="meta">Posição ${v.position} · ${esc(v.version)}</span></div><span class="pill">${v.is_active?'ATIVO':'PAUSADO'}</span></div><p>“${esc(v.text)}”</p><button class="button small danger" onclick="deleteDaily(${v.id})">Excluir</button></div>`).join('')||'<div class="empty">Nenhum versículo agendado.</div>'}catch(e){toast(e.message,true)}}
$('dailyForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);const data=Object.fromEntries(f);data.position=Number(data.position);data.chapter=data.chapter?Number(data.chapter):null;data.verse_number=data.verse_number?Number(data.verse_number):null;data.is_active=f.has('is_active');try{await api('/admin/daily-verses',{method:'POST',body:JSON.stringify(data)});e.target.reset();toast('Versículo agendado');loadDaily()}catch(err){toast(err.message,true)}});
async function deleteDaily(id){if(!confirm('Excluir este agendamento?'))return;try{await api('/admin/daily-verses/'+id,{method:'DELETE'});loadDaily()}catch(e){toast(e.message,true)}}
async function loadPush(){try{const {data}=await api('/admin/push-campaigns');$('deviceCount').textContent=data.devices.total+' aparelhos';$('pushList').innerHTML=data.campaigns.data.map(c=>`<div class="item"><div class="item-head"><div><strong>${esc(c.title)}</strong><span class="meta">${esc(c.audience)} · ${esc(c.status)}</span></div><span class="pill">${c.sent_count}/${c.target_count}</span></div><p>${esc(c.body)}</p>${['draft','scheduled','failed'].includes(c.status)?`<button class="button small" onclick="sendPush(${c.id})">Enviar agora</button>`:''}</div>`).join('')||'<div class="empty">Nenhuma campanha.</div>'}catch(e){toast(e.message,true)}}
$('pushForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);const reference=f.get('reference');const data={title:f.get('title'),body:f.get('body'),audience:f.get('audience'),scheduled_at:f.get('scheduled_at')||null,send_now:f.has('send_now'),data:reference?{reference,version:f.get('version')||'NVI'}:{path:'/community'}};try{await api('/admin/push-campaigns',{method:'POST',body:JSON.stringify(data)});e.target.reset();toast('Campanha salva');loadPush()}catch(err){toast(err.message,true)}});
async function sendPush(id){if(!confirm('Enviar esta campanha agora?'))return;try{await api('/admin/push-campaigns/'+id+'/send',{method:'POST'});toast('Campanha colocada na fila');loadPush()}catch(e){toast(e.message,true)}}
async function loadCategories(){try{const [cats,groups]=await Promise.all([api('/admin/categories/pending'),api('/admin/category-groups/pending')]);$('categoriesList').innerHTML=(cats.data.data||cats.data||[]).map(c=>pending(c,'categories')).join('')||'<div class="empty">Tudo aprovado.</div>';$('groupsList').innerHTML=(groups.data.data||groups.data||[]).map(c=>pending(c,'category-groups')).join('')||'<div class="empty">Tudo aprovado.</div>'}catch(e){toast(e.message,true)}}
function pending(c,type){return `<div class="item"><strong>${esc(c.name)}</strong><span class="meta">${esc(c.description||'Sem descrição')}</span><div class="actions"><button class="button small" onclick="approve('${type}',${c.id},true)">Aprovar</button><button class="button small danger" onclick="approve('${type}',${c.id},false)">Rejeitar</button></div></div>`}async function approve(type,id,ok){const reason=ok?'Aprovado pelo painel':prompt('Motivo da rejeição');if(!ok&&!reason)return;try{await api('/admin/'+type+'/'+id+'/'+(ok?'approve':'reject'),{method:'POST',body:JSON.stringify(ok?{notes:reason}:{reason})});loadCategories()}catch(e){toast(e.message,true)}}
async function searchBible(){const q=$('bibleSearch').value.trim();if(q.length<2)return;try{const {data}=await api('/bible/nvi/search?q='+encodeURIComponent(q));$('bibleList').innerHTML=(Array.isArray(data)?data:[]).map(v=>`<div class="item"><strong>${esc(v.reference)}</strong><p>“${esc(v.text)}”</p></div>`).join('')||'<div class="empty">Nenhum resultado.</div>'}catch(e){toast(e.message,true)}}
$('logout').onclick=logout;$('clock').textContent=new Date().toLocaleString('pt-BR');boot();
</script>
</body>
</html>
